name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 18 1-7 * SAT'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-multilib scons
      - name: Build
        run: ./build
      - name: Test
        run: ./test
  linux-ubsan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ scons
      - name: Build
        run: ./build arch=x64 sanitize=undefined
      - name: Test
        run: ./out/ReleaseUBSanX64/primordialsoup out/snapshots/TestRunner.vfuel
        env:
          UBSAN_OPTIONS: halt_on_error=1
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install scons
      - name: Build
        run: ./build
      - name: Test
        run: ./test
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install scons
      - name: Build
        run: build.bat
        shell: cmd
      - name: Test
        run: test.bat
        shell: cmd
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++-multilib scons
      - name: Build
        run: ./build ndk=$ANDROID_NDK
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install g++ scons
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
      - name: Build
        run: ./build os=emscripten arch=wasm
      - name: Test
        run: ./.github/workflows/test-web-xvfb
